// eslint-disable-next-line import/no-anonymous-default-export
export default {
  "login": "Kabe3r",
  "id": 94847995,
  "node_id": "U_kgDOBadD-w",
  "avatar_url": "https://avatars.githubusercontent.com/u/94847995?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Kabe3r",
  "html_url": "https://github.com/Kabe3r",
  "followers_url": "https://api.github.com/users/Kabe3r/followers",
  "following_url": "https://api.github.com/users/Kabe3r/following{/other_user}",
  "gists_url": "https://api.github.com/users/Kabe3r/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Kabe3r/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Kabe3r/subscriptions",
  "organizations_url": "https://api.github.com/users/Kabe3r/orgs",
  "repos_url": "https://api.github.com/users/Kabe3r/repos",
  "events_url": "https://api.github.com/users/Kabe3r/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Kabe3r/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Ahmed Ali",
  "company": null,
  "blog": "",
  "location": "Pakistan",
  "email": null,
  "hireable": null,
  "bio": "Front End Developer",
  "twitter_username": null,
  "public_repos": 20,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2021-11-22T13:57:32Z",
  "updated_at": "2022-12-04T17:11:57Z"
};
